name = "YahooFinance"
uuid = "71b753c1-733f-4418-b8b2-c1bb484780f7"
authors = ["markushhh <markushhh.jl@gmail.com>"]
version = "0.2.2"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"

[compat]
DataFrames = " 0.19.0,0.20.0"
Dates = "1.2.0"
HTTP = "1.10"
JSON = "0.21.0"
TimeSeries = "0.16.1"
julia = "1"
